---
{
   "kind": "pipeline",
   "name": "Codequality",
   "steps": [
      {
         "commands": [
            "php -v",
            "composer update",
            "composer require phpmd/phpmd phpstan/phpstan"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards",
            "vendor/bin/phpcs --standard=ruleset.xml src/"
         ],
         "depends": [
            "composer"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcs"
      },
      {
         "commands": [
            "vendor/bin/phpmd src text cleancode",
            "vendor/bin/phpmd src text codesize",
            "vendor/bin/phpmd src text controversial",
            "vendor/bin/phpmd src text design",
            "vendor/bin/phpmd src text unusedcode"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpmd"
      },
      {
         "commands": [
            "vendor/bin/phpstan analyse src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpstan"
      },
      {
         "commands": [
            "phploc src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phploc"
      },
      {
         "commands": [
            "phpcpd src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcpd"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "sqlsrv"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MS SQL Server 2017-latest (sqlsrv)",
   "services": [
      {
         "environment": {
            "ACCEPT_EULA": "Y",
            "SA_PASSWORD": "JoomlaFramework123"
         },
         "image": "mcr.microsoft.com/mssql/server:2017-latest",
         "name": "mssql-server",
         "ports": [
            {
               "container": 1433,
               "host": 1433
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y software-properties-common gnupg",
            "apt-key adv --fetch-keys \"https://packages.sury.org/php/apt.gpg\" > /dev/null 2>&1",
            "echo \"deb https://packages.sury.org/php/ bullseye main\" >> /etc/apt/sources.list",
            "cat /etc/apt/sources.list",
            "apt-get update",
            "apt-get install -y php7.4-dev gcc musl-dev make",
            "pecl install sqlsrv pdo_sqlsrv && docker-php-ext-enable sqlsrv pdo_sqlsrv"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Install MS SQL Server"
      },
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "vendor/bin/phpunit --configuration ./.travis/phpunit.sqlsrv.xml"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
kind: signature
hmac: bbe121cb7334dceb6d2ab27742cac1440c2e0de906a1f52c309033f562dd72c5

...
