---
{
   "kind": "pipeline",
   "name": "Codequality",
   "steps": [
      {
         "commands": [
            "php -v",
            "composer update",
            "composer require phpmd/phpmd phpstan/phpstan"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards",
            "vendor/bin/phpcs --standard=ruleset.xml src/"
         ],
         "depends": [
            "composer"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcs"
      },
      {
         "commands": [
            "vendor/bin/phpmd src text cleancode",
            "vendor/bin/phpmd src text codesize",
            "vendor/bin/phpmd src text controversial",
            "vendor/bin/phpmd src text design",
            "vendor/bin/phpmd src text unusedcode"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpmd"
      },
      {
         "commands": [
            "vendor/bin/phpstan analyse src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpstan"
      },
      {
         "commands": [
            "phploc src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phploc"
      },
      {
         "commands": [
            "phpcpd src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcpd"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "sqlite"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with SQLite (sqlite)",
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri sqlite || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.sqlite.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysql"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MySQL 5.7 (mysql)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysql"
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysql || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.mysql.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysql"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MySQL 8.0 (mysql)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysql"
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysql || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.mysql.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysql"
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.mysqli.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MySQL 8.0 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysql"
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.mysqli.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mariadb"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MariaDB 10.2 (mariadb)",
   "services": [
      {
         "environment": {
            "MARIADB_ALLOW_EMPTY_ROOT_PASSWORD": "yes",
            "MARIADB_DATABASE": "joomla_ut",
            "MARIADB_ROOT_PASSWORD": ""
         },
         "image": "mariadb:10.2",
         "name": "mariadb"
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mariadb || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.mariadb.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "pgsql"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with PostgreSQL 10 (pgsql)",
   "services": [
      {
         "commands": [
            "psql -U postgres -c 'create database joomla_ut;'",
            "psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql"
         ],
         "environment": {
            "POSTGRES_HOST_AUTH_METHOD": "trust",
            "POSTGRES_PASSWORD": "",
            "POSTGRES_USER": "postgres"
         },
         "image": "postgres:10",
         "name": "postgresql",
         "ports": [
            {
               "container": 5432,
               "host": 5432
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri pgsql || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.pgsql.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "pgsql"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with PostgreSQL 11 (pgsql)",
   "services": [
      {
         "commands": [
            "psql -U postgres -c 'create database joomla_ut;'",
            "psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql"
         ],
         "environment": {
            "POSTGRES_HOST_AUTH_METHOD": "trust",
            "POSTGRES_PASSWORD": "",
            "POSTGRES_USER": "postgres"
         },
         "image": "postgres:11",
         "name": "postgresql",
         "ports": [
            {
               "container": 5432,
               "host": 5432
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri pgsql || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.pgsql.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "sqlsrv"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MS SQL Server 2017-latest (sqlsrv)",
   "services": [
      {
         "environment": {
            "ACCEPT_EULA": "Y",
            "SA_PASSWORD": "JoomlaFramework123"
         },
         "image": "mcr.microsoft.com/mssql/server:2017-latest",
         "name": "mssql-server",
         "ports": [
            {
               "container": 1433,
               "host": 1433
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "export DEBIAN_FRONTEND=noninteractive",
            "apt-get -qq update",
            "apt-get -qq install -y software-properties-common lsb-release gnupg",
            "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -",
            "echo \"deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/debian/11/prod bullseye main\" >> /etc/apt/sources.list",
            "apt-get -qq update",
            "ACCEPT_EULA=Y apt-get -qq install -y msodbcsql18 unixodbc-dev",
            "pecl install sqlsrv && docker-php-ext-enable sqlsrv",
            "pecl install pdo_sqlsrv && docker-php-ext-enable pdo_sqlsrv",
            "php --ri sqlsrv",
            "php --ri pdo_sqlsrv"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHP binding for MS SQL Server"
      },
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri sqlsrv || true",
            "vendor/bin/phpunit --configuration ./.travis/phpunit.sqlsrv.xml --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
kind: signature
hmac: 0f3f7bad5f0c1639968e257e0d0e3101628b032983bcb2189221b24405a9ba4b

...
