---
{
   "kind": "pipeline",
   "name": "Codequality",
   "steps": [
      {
         "commands": [
            "php -v",
            "composer update",
            "composer require phpmd/phpmd phpstan/phpstan"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards",
            "vendor/bin/phpcs --standard=ruleset.xml src/"
         ],
         "depends": [
            "composer"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcs"
      },
      {
         "commands": [
            "vendor/bin/phpmd src text cleancode",
            "vendor/bin/phpmd src text codesize",
            "vendor/bin/phpmd src text controversial",
            "vendor/bin/phpmd src text design",
            "vendor/bin/phpmd src text unusedcode"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpmd"
      },
      {
         "commands": [
            "vendor/bin/phpstan analyse src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpstan"
      },
      {
         "commands": [
            "phploc src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phploc"
      },
      {
         "commands": [
            "phpcpd src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcpd"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "sqlsrv"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MS SQL Server 2017-latest (sqlsrv)",
   "services": [
      {
         "environment": {
            "ACCEPT_EULA": "Y",
            "SA_PASSWORD": "JoomlaFramework123"
         },
         "image": "mcr.microsoft.com/mssql/server:2017-latest",
         "name": "mssql-server",
         "ports": [
            {
               "container": 1433,
               "host": 1433
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y software-properties-common lsb-release gnupg",
            "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -",
            "echo \"deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/debian/11/prod bullseye main\" >> /etc/apt/sources.list",
            "apt-get update",
            "ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev",
            "pecl install sqlsrv pdo_sqlsrv && docker-php-ext-enable sqlsrv pdo_sqlsrv"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Install MS SQL Server"
      },
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "vendor/bin/phpunit --configuration ./.travis/phpunit.sqlsrv.xml"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
kind: signature
hmac: 25c36e298254777eb78fa0ec09021603eb46639c8b37ff4927cee23ea6135f5b

...
