---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  - composer require phpmd/phpmd phpstan/phpstan
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
  - vendor/bin/phpcs --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php7.4
  name: phpcs
- commands:
  - vendor/bin/phpmd src text cleancode
  - vendor/bin/phpmd src text codesize
  - vendor/bin/phpmd src text controversial
  - vendor/bin/phpmd src text design
  - vendor/bin/phpmd src text unusedcode
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phpmd
- commands:
  - vendor/bin/phpstan analyse src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php7.4
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: sqlite
kind: pipeline
name: PHP 7.4 with SQLite (sqlite)
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.sqlite.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: mysql.docker
kind: pipeline
name: PHP 7.4 with MySQL 5.7 (mysql.docker)
services:
- commands:
  - bash <<< 'until echo \q | mysql joomla_ut > /dev/null 2>&1 ; do sleep 1; done'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: joomla_ut
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_USER: root
  image: mysql:5.7
  name: mysql
  ports:
  - container: 3306
    host: 33306
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.mysql.docker.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: mysql.docker
kind: pipeline
name: PHP 7.4 with MySQL 8.0 (mysql.docker)
services:
- commands:
  - bash <<< 'until echo \q | mysql joomla_ut > /dev/null 2>&1 ; do sleep 1; done'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: joomla_ut
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_USER: root
  image: mysql:8.0
  name: mysql
  ports:
  - container: 3306
    host: 33306
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.mysql.docker.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: mysqli.docker
kind: pipeline
name: PHP 7.4 with MySQL 5.7 (mysqli.docker)
services:
- commands:
  - bash <<< 'until echo \q | mysql joomla_ut > /dev/null 2>&1 ; do sleep 1; done'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: joomla_ut
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_USER: root
  image: mysql:5.7
  name: mysql
  ports:
  - container: 3306
    host: 33306
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.mysqli.docker.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: mysqli.docker
kind: pipeline
name: PHP 7.4 with MySQL 8.0 (mysqli.docker)
services:
- commands:
  - bash <<< 'until echo \q | mysql joomla_ut > /dev/null 2>&1 ; do sleep 1; done'
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: joomla_ut
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_USER: root
  image: mysql:8.0
  name: mysql
  ports:
  - container: 3306
    host: 33306
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.mysqli.docker.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: mariadb
kind: pipeline
name: PHP 7.4 with MariaDB 10.2 (mariadb)
services:
- commands:
  - bash <<< 'until echo \q | mysql joomla_ut > /dev/null 2>&1 ; do sleep 1; done'
  environment:
    MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
    MARIADB_DATABASE: joomla_ut
    MARIADB_PASSWORD: ""
    MARIADB_ROOT_PASSWORD: ""
    MARIADB_USER: root
  image: mariadb:10.2
  name: mariadb
  ports:
  - container: 3306
    host: 33306
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.mariadb.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: pgsql
kind: pipeline
name: PHP 7.4 with PostgreSQL 10 (pgsql)
services:
- commands:
  - bash <<< 'until pg_isready -U postgres > /dev/null 2>&1 ; do sleep 1; done'
  - psql -U postgres -c 'create database joomla_ut;'
  - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: postgres
  image: postgres:10
  name: postgresql
  ports:
  - container: 5432
    host: 5432
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.pgsql.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: pgsql
kind: pipeline
name: PHP 7.4 with PostgreSQL 11 (pgsql)
services:
- commands:
  - bash <<< 'until pg_isready -U postgres > /dev/null 2>&1 ; do sleep 1; done'
  - psql -U postgres -c 'create database joomla_ut;'
  - psql -U postgres -d joomla_ut -a -f Tests/Stubs/Schema/pgsql.sql
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: ""
    POSTGRES_USER: postgres
  image: postgres:11
  name: postgresql
  ports:
  - container: 5432
    host: 5432
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.pgsql.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
environment:
  DB: sqlsrv
kind: pipeline
name: PHP 7.4 with MS SQL Server 2017-latest (sqlsrv)
services:
- commands:
  - bash <<< 'retries=10; echo 'Waiting for SQL Server to start...'; until (echo quit
    | /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -l 1 -U sa -P JoomlaFramework123 &>
    /dev/null) do if [[ "$retries" -le 0 ]]; then echo 'SQL Server did not start';
    exit 1; fi; retries=$((retries - 1)); sleep 2s; done; echo 'SQL Server started'
  environment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: JoomlaFramework123
  image: mcr.microsoft.com/mssql/server:2017-latest
  name: mssql-server
  ports:
  - container: 1433
    host: 1433
steps:
- commands:
  - php -v
  - sleep 15
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php7.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit --configuration ./.travis/phpunit.sqlsrv.xml
  image: joomlaprojects/docker-images:php7.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: d6874d04bdad1fa1e69dcbfb30573aac33e4d964af266a0656d4ad81d5b3662a

...
