---
{
   "kind": "pipeline",
   "name": "Codequality",
   "steps": [
      {
         "commands": [
            "php -v",
            "composer update",
            "composer require phpmd/phpmd phpstan/phpstan"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards",
            "vendor/bin/phpcs --standard=ruleset.xml src/"
         ],
         "depends": [
            "composer"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcs"
      },
      {
         "commands": [
            "vendor/bin/phpmd src text cleancode",
            "vendor/bin/phpmd src text codesize",
            "vendor/bin/phpmd src text controversial",
            "vendor/bin/phpmd src text design",
            "vendor/bin/phpmd src text unusedcode"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpmd"
      },
      {
         "commands": [
            "vendor/bin/phpstan analyse src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpstan"
      },
      {
         "commands": [
            "phploc src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phploc"
      },
      {
         "commands": [
            "phpcpd src"
         ],
         "depends": [
            "composer"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "phpcpd"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.2 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --prefer-lowest"
         ],
         "image": "joomlaprojects/docker-images:php7.2",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.2",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.3 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.3",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.3",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 8.0 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --ignore-platform-reqs"
         ],
         "image": "joomlaprojects/docker-images:php8.0",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php8.0",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 8.1 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --ignore-platform-reqs"
         ],
         "image": "joomlaprojects/docker-images:php8.1",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php8.1",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 8.2 with MySQL 5.7 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:5.7",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --ignore-platform-reqs"
         ],
         "image": "joomlaprojects/docker-images:php8.2",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php8.2",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.3 with MySQL 8.0 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.3",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.3",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 7.4 with MySQL 8.0 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php7.4",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 8.0 with MySQL 8.0 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --ignore-platform-reqs"
         ],
         "image": "joomlaprojects/docker-images:php8.0",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php8.0",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 8.1 with MySQL 8.0 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --ignore-platform-reqs"
         ],
         "image": "joomlaprojects/docker-images:php8.1",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "image": "joomlaprojects/docker-images:php8.1",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
{
   "environment": {
      "DB": "mysqli"
   },
   "kind": "pipeline",
   "name": "PHP 8.2 with MySQL 8.0 (mysqli)",
   "services": [
      {
         "environment": {
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
            "MYSQL_AUTHENTICATION_PLUGIN": "mysql_native_password",
            "MYSQL_DATABASE": "joomla_ut",
            "MYSQL_ROOT_PASSWORD": ""
         },
         "image": "mysql:8.0",
         "name": "mysqli",
         "ports": [
            {
               "container": 3306,
               "host": 3306
            }
         ]
      }
   ],
   "steps": [
      {
         "commands": [
            "php -v",
            "sleep 20",
            "composer update --prefer-stable --ignore-platform-reqs"
         ],
         "image": "joomlaprojects/docker-images:php8.2",
         "name": "Composer",
         "volumes": [
            {
               "name": "composer-cache",
               "path": "/tmp/composer-cache"
            }
         ]
      },
      {
         "commands": [
            "php --ri mysqli || true",
            "sleep 20",
            "vendor/bin/phpunit --configuration phpunit.mysqli.xml.dist --testdox"
         ],
         "failure": "ignore",
         "image": "joomlaprojects/docker-images:php8.2",
         "name": "PHPUnit"
      }
   ],
   "volumes": [
      {
         "host": {
            "path": "/tmp/composer-cache"
         },
         "name": "composer-cache"
      }
   ]
}
---
kind: signature
hmac: 6a7e9dd00090f670042ab03adbcb05f37b2a6f1cc7d59e4cfc00bc0504d467db

...
